sales_project/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'home/index'
  resources :order_items
  resources :orders
  resources :products
  resources :customers
  resources :employees
  resources :shippers
  resources :suppliers
  resources :categories
  
  root to:'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sales_project/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

sales_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sales_project/app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  
  validates :description, presence: true
  
end

sales_project/app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :phone, presence: true, uniqueness: true
  validates :birthday, presence: true
  validates :email, presence: true, uniqueness: true
end

sales_project/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :orders
  
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :phone, presence: true
  validates :birthday, presence: true
  
end

sales_project/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :shipper
  belongs_to :employee
  belongs_to :customer
  has_many :order_items
  
  has_many :products, through: :order_item 
end

sales_project/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  
  validates :quantity, presence: true
  
end

sales_project/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier
  belongs_to :category
  has_many :order_items
  
  validates :description, presence: true
  validates :quantity_per_unit, presence: true
  validates :unit_price, presence: true
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

sales_project/app/models/shipper.rb
class Shipper < ApplicationRecord
  has_many :orders
  
  validates :description, presence: true
  
end

sales_project/app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
  
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  
end

sales_project/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!
  
  def index
  end
end

sales_project/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:shipper_id, :employee_id, :customer_id, :description, :order_date)
    end
end

sales_project/app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!

  # GET /suppliers or /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1 or /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers or /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to supplier_url(@supplier), notice: "Supplier was successfully created." }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1 or /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to supplier_url(@supplier), notice: "Supplier was successfully updated." }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1 or /suppliers/1.json
  def destroy
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: "Supplier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_params
      params.require(:supplier).permit(:description, :address, :city, :state)
    end
end

sales_project/app/helpers/application_helper.rb
module ApplicationHelper
end

sales_project/app/helpers/categories_helper.rb
module CategoriesHelper
end

sales_project/app/helpers/customers_helper.rb
module CustomersHelper
end

sales_project/app/helpers/employees_helper.rb
module EmployeesHelper
end

sales_project/app/helpers/home_helper.rb
module HomeHelper
end

sales_project/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

sales_project/app/helpers/orders_helper.rb
module OrdersHelper
end

sales_project/app/helpers/products_helper.rb
module ProductsHelper
end

sales_project/app/helpers/shippers_helper.rb
module ShippersHelper
end

sales_project/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

sales_project/app/views/suppliers/_form.html.erb
<%= form_with(model: supplier, local: true) do |form| %>
  <% if supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% supplier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sales_project/app/views/suppliers/edit.html.erb
<h1>Editing Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

sales_project/app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suppliers</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.description %></td>
        <td><%= supplier.address %></td>
        <td><%= supplier.city %></td>
        <td><%= supplier.state %></td>
        <td><%= link_to 'Show', supplier %></td>
        <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
        <td><%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New', new_supplier_path %> | 
<%= link_to 'Back', home_index_path %>

sales_project/app/views/suppliers/new.html.erb
<h1>New Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Back', suppliers_path %>

sales_project/app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @supplier.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @supplier.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @supplier.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @supplier.state %>
</p>

<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>