sales_project/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'home/index'
  resources :order_items
  resources :orders
  resources :products
  resources :customers
  resources :employees
  resources :shippers
  resources :suppliers
  resources :categories
  
  root to:'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sales_project/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

sales_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sales_project/app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  
  validates :description, presence: true
  
end

sales_project/app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :phone, presence: true, uniqueness: true
  validates :birthday, presence: true
  validates :email, presence: true, uniqueness: true
end

sales_project/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :orders
  
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :phone, presence: true
  validates :birthday, presence: true
  
end

sales_project/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :shipper
  belongs_to :employee
  belongs_to :customer
  has_many :order_items
  
  has_many :products, through: :order_item 
end

sales_project/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  
  validates :quantity, presence: true
  
end

sales_project/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier
  belongs_to :category
  has_many :order_items
  
  validates :description, presence: true
  validates :quantity_per_unit, presence: true
  validates :unit_price, presence: true
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

sales_project/app/models/shipper.rb
class Shipper < ApplicationRecord
  has_many :orders
  
  validates :description, presence: true
  
end

sales_project/app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
  
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  
end

sales_project/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!
  
  def index
  end
end

sales_project/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:shipper_id, :employee_id, :customer_id, :description, :order_date)
    end
end

sales_project/app/helpers/application_helper.rb
module ApplicationHelper
end

sales_project/app/helpers/categories_helper.rb
module CategoriesHelper
end

sales_project/app/helpers/customers_helper.rb
module CustomersHelper
end

sales_project/app/helpers/employees_helper.rb
module EmployeesHelper
end

sales_project/app/helpers/home_helper.rb
module HomeHelper
end

sales_project/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

sales_project/app/helpers/orders_helper.rb
module OrdersHelper
end

sales_project/app/helpers/products_helper.rb
module ProductsHelper
end

sales_project/app/helpers/shippers_helper.rb
module ShippersHelper
end

sales_project/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

sales_project/app/views/home/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Dashboard Template · Bootstrap v5.2</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/dashboard/">
    <link href="/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .pequeno {
        width: 20%;
      }

      .medio {
        width: 85%;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="home.css" rel="stylesheet">
  </head>
  <body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6">SALES - Project</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-nav">
        <div class="nav-item text-nowrap">
          <ul class="nav flex-column">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6"> <%= current_admin.email %>  </a>
                <a class="nav-item"><%= link_to 'Sign Out', destroy_admin_session_path, method: :delete, class:"btn btn-danger btn-sm", role:"button" %></a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu" class="navbar-brand col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-3 sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link"><%= link_to 'Order Items', order_items_path, class:"btn btn-primary btn-sm medio btn-dark", role:"button" %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link"><%= link_to 'Order', orders_path, class:"btn btn-primary btn-sm medio btn-dark", role:"button" %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link"><%= link_to 'Product', products_path, class:"btn btn-primary btn-sm medio btn-dark", role:"button" %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link"><%= link_to 'Category', categories_path, class:"btn btn-primary btn-sm medio btn-dark", role:"button" %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link"><%= link_to 'Supplier', suppliers_path, class:"btn btn-primary btn-sm medio btn-dark", role:"button" %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link"><%= link_to 'Customer', customers_path, class:"btn btn-primary btn-sm medio btn-dark", role:"button" %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link"><%= link_to 'Employee', employees_path, class:"btn btn-primary btn-sm medio btn-dark", role:"button" %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link"><%= link_to 'Shipper', shippers_path, class:"btn btn-primary btn-sm medio btn-dark", role:"button" %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link"><%= link_to 'Sobre', shippers_path, class:"btn btn-primary btn-sm medio btn-dark", role:"button" %></a>
              </li>
            </ul>
          </div>
        </nav>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
            </div>
          </div>
          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>
          <h2>Pablo Wendrey Sousa Marinho</h2>
            <div class="table-responsive">
              <table class="table table-striped table-sm">
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>
    <script src="/node_modules/bootstrap/dist/js/bootstrap.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="home.js"></script>
  </body>
</html>