sales_project/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'home/index'
  resources :order_items
  resources :orders
  resources :products
  resources :customers
  resources :employees
  resources :shippers
  resources :suppliers
  resources :categories
  
  root to:'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sales_project/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

sales_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sales_project/app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  
  validates :description, presence: true
  
end

sales_project/app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :phone, presence: true, uniqueness: true
  validates :birthday, presence: true
  validates :email, presence: true, uniqueness: true
end

sales_project/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :orders
  
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :phone, presence: true
  validates :birthday, presence: true
  
end

sales_project/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :shipper
  belongs_to :employee
  belongs_to :customer
  has_many :order_items
  
  has_many :products, through: :order_item 
end

sales_project/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  
  validates :quantity, presence: true
  
end

sales_project/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier
  belongs_to :category
  has_many :order_items
  
  validates :description, presence: true
  validates :quantity_per_unit, presence: true
  validates :unit_price, presence: true
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

sales_project/app/models/shipper.rb
class Shipper < ApplicationRecord
  has_many :orders
  
  validates :description, presence: true
  
end

sales_project/app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
  
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  
end

sales_project/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!
  
  def index
  end
end

sales_project/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:shipper_id, :employee_id, :customer_id, :description, :order_date)
    end
end

sales_project/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:supplier_id, :category_id, :description, :quantity_per_unit, :unit_price, :image)
    end
end

sales_project/app/helpers/application_helper.rb
module ApplicationHelper
end

sales_project/app/helpers/categories_helper.rb
module CategoriesHelper
end

sales_project/app/helpers/customers_helper.rb
module CustomersHelper
end

sales_project/app/helpers/employees_helper.rb
module EmployeesHelper
end

sales_project/app/helpers/home_helper.rb
module HomeHelper
end

sales_project/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

sales_project/app/helpers/orders_helper.rb
module OrdersHelper
end

sales_project/app/helpers/products_helper.rb
module ProductsHelper
end

sales_project/app/helpers/shippers_helper.rb
module ShippersHelper
end

sales_project/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

sales_project/app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :shipper_id %>
    <%= form.select("shipper_id", Shipper.all.pluck(:description, :id), {inclue_blank: 'Selecione...' }) %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.select("employee_id", Employee.all.pluck(:description, :id), {inclue_blank: 'Selecione...' }) %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.select("customer_id", Customer.all.pluck(:description, :id), {inclue_blank: 'Selecione...' }) %>
  </div>

  <div class="field">
    <%= form.label :order_date %>
    <%= form.date_select :order_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sales_project/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

sales_project/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Shipper</th>
      <th>Employee</th>
      <th>Customer</th>
      <th>Order date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.shipper.description %></td>
        <td><%= order.employee.description %></td>
        <td><%= order.customer.description %></td>
        <td><%= order.order_date %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New', new_order_path %> | 
<%= link_to 'Back', home_index_path %>

sales_project/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

sales_project/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shipper:</strong>
  <%= @order.shipper.description %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @order.employee.description %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer.description %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @order.order_date %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

sales_project/app/views/products/_form.html.erb
<%= form_with(model: product, local: true, :html => {:multipart => true }) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.select("supplier_id", Supplier.all.pluck(:description, :id), {inclue_blank: 'Selecione...' }) %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select("category_id", Category.all.pluck(:description, :id), {inclue_blank: 'Selecione...' }) %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :quantity_per_unit %>
    <%= form.number_field :quantity_per_unit %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.text_field :unit_price %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sales_project/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

sales_project/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Supplier</th>
      <th>Category</th>
      <th>Description</th>
      <th>Quantity per unit</th>
      <th>Unit price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.supplier.description %></td>
        <td><%= product.category.description %></td>
        <td><%= product.description %></td>
        <td><%= product.quantity_per_unit %></td>
        <td><%= product.unit_price %></td>
        <td><%= image_tag product.image.url(:thumb) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New', new_product_path %> | 
<%= link_to 'Back', home_index_path %>

sales_project/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

sales_project/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier:</strong>
  <%= @product.supplier.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.description %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Quantity per unit:</strong>
  <%= @product.quantity_per_unit %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @product.unit_price %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image.url(:medium) %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>